exec-once = /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots"
exec-once = "export QT_QPA_PLATFORM=wayland"
exec-once = "/usr/lib/polkit-kde-authentication-agent-1"
exec-once = /usr/lib/xdg-desktop-portal-wlr 
exec-once = bluetooth off
exec-once = swww-daemon
exec-once = env GSK_RENDER=gl vibepanel
exe-once = waypaper --restore &
exec-once = ~/.config/mango/scripts/vipanel.sh

