# Window rules
windowrule = isterm:1,appid:kitty
windowrule = allow_csd:0,appid:*
windowrule = isfloating:1,title:"File Operation Process"
windowrule = isfloating:1,isnamedscratchpad:1,title:"Notes"

# scratch pad
scratchpad_width_ratio=0.4
scratchpad_height_ratio=0.4
