[bar]
position = "top"
size = 35
screen_margin = 0
spacing = 4
inset = 0
padding = 0
border_radius = 0
background_opacity = 0.5
background_color = "#18120c"

[widgets]
left = ["workspaces", "window_title"]
center = ["media"]
right = [{ group = ["cpu", "memory"] },{ group = ["quick_settings", "battery"] }, "clock", "notifications"]
border_radius = 0
background_opacity = 1.0
background_color = "#504539"

[widgets.workspaces]
label_type = "index"
background_color = "#f8bb71"

[widgets.window_title]
background_color = "#dfc1a2"

[widgets.cpu]
background_color = "#bccd9e"

[widgets.memory]
format = "percentage"
background_color = "#bccd9e"

[widgets.clock]
format = "%A %H:%M"
background_color = "#663e00"

[widgets.notifications]
background_color = "#ffb4ab"

[theme]
accent = "#f8bb71"

