$image = Null

$background = rgba(18120cff)

$blue = rgba(b8c4ffff)

$blue_container = rgba(374379ff)

$blue_source = rgba(89b4faff)

$blue_value = rgba(89b4faff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$green = rgba(b1d18aff)

$green_container = rgba(354e16ff)

$green_source = rgba(a6e3a1ff)

$green_value = rgba(a6e3a1ff)

$inverse_on_surface = rgba(372f27ff)

$inverse_primary = rgba(825514ff)

$inverse_surface = rgba(eee0d4ff)

$on_background = rgba(eee0d4ff)

$on_blue = rgba(1f2c61ff)

$on_blue_container = rgba(dde1ffff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_green = rgba(1f3701ff)

$on_green_container = rgba(cdeda3ff)

$on_orange = rgba(4c2700ff)

$on_orange_container = rgba(ffdcc1ff)

$on_primary = rgba(472a00ff)

$on_primary_container = rgba(ffddb9ff)

$on_primary_fixed = rgba(2b1700ff)

$on_primary_fixed_variant = rgba(663e00ff)

$on_purple = rgba(462152ff)

$on_purple_container = rgba(fad7ffff)

$on_red = rgba(561d20ff)

$on_red_container = rgba(ffdad9ff)

$on_secondary = rgba(3f2d17ff)

$on_secondary_container = rgba(fdddbdff)

$on_secondary_fixed = rgba(281805ff)

$on_secondary_fixed_variant = rgba(57432bff)

$on_surface = rgba(eee0d4ff)

$on_surface_variant = rgba(d4c4b5ff)

$on_tertiary = rgba(273513ff)

$on_tertiary_container = rgba(d7e9b8ff)

$on_tertiary_fixed = rgba(131f02ff)

$on_tertiary_fixed_variant = rgba(3d4b27ff)

$on_yellow = rgba(422c00ff)

$on_yellow_container = rgba(ffdeabff)

$orange = rgba(ffb878ff)

$orange_container = rgba(6b3b04ff)

$orange_source = rgba(fab387ff)

$orange_value = rgba(fab387ff)

$outline = rgba(9c8e81ff)

$outline_variant = rgba(504539ff)

$primary = rgba(f8bb71ff)

$primary_container = rgba(663e00ff)

$primary_fixed = rgba(ffddb9ff)

$primary_fixed_dim = rgba(f8bb71ff)

$purple = rgba(e6b6f1ff)

$purple_container = rgba(5e386aff)

$purple_source = rgba(cba6f7ff)

$purple_value = rgba(cba6f7ff)

$red = rgba(ffb3b3ff)

$red_container = rgba(733335ff)

$red_source = rgba(f38ba8ff)

$red_value = rgba(f38ba8ff)

$scrim = rgba(000000ff)

$secondary = rgba(dfc1a2ff)

$secondary_container = rgba(57432bff)

$secondary_fixed = rgba(fdddbdff)

$secondary_fixed_dim = rgba(dfc1a2ff)

$shadow = rgba(000000ff)

$source_color = rgba(292016ff)

$surface = rgba(18120cff)

$surface_bright = rgba(403830ff)

$surface_container = rgba(251e17ff)

$surface_container_high = rgba(302921ff)

$surface_container_highest = rgba(3b332cff)

$surface_container_low = rgba(211a13ff)

$surface_container_lowest = rgba(130d07ff)

$surface_dim = rgba(18120cff)

$surface_tint = rgba(f8bb71ff)

$surface_variant = rgba(504539ff)

$tertiary = rgba(bccd9eff)

$tertiary_container = rgba(3d4b27ff)

$tertiary_fixed = rgba(d7e9b8ff)

$tertiary_fixed_dim = rgba(bccd9eff)

$yellow = rgba(efbf6dff)

$yellow_container = rgba(5f4100ff)

$yellow_source = rgba(f9e2afff)

$yellow_value = rgba(f9e2afff)

