# : Manager [[[

[mgr]
cwd = { fg = "#eee0d4" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#abd16a", bg = "#abd16a" }
marker_cut      = { fg = "#d7e9b8", bg = "#d7e9b8" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#bccd9e", bg = "#bccd9e" }

# Count
count_copied   = { fg = "#131f02", bg = "#d7e9b8" }
count_cut      = { fg = "#131f02", bg = "#d7e9b8" }
count_selected = { fg = "#472a00", bg = "#bccd9e" }

# Border
border_symbol = "│"
border_style  = { fg = "#f8bb71" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#f8bb71", bold = true, bg = "#18120c" }
inactive  = { fg = "#dfc1a2", bg = "#18120c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#f8bb71", fg = "#472a00", bold = true }
normal_alt  = { bg = "#504539", fg = "#d4c4b5" }

# Select mode
select_main = { bg = "#dfc1a2", fg = "#3f2d17", bold = true }
select_alt  = { bg = "#504539", fg = "#d4c4b5" }

# Unset mode
unset_main = { bg = "#bccd9e", fg = "#273513", bold = true }
unset_alt  = { bg = "#504539", fg = "#d4c4b5" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#ad753b" }
perm_write = { fg = "#728b47" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#95c543" }
perm_sep   = { fg = "#ff9320" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#f8bb71", bg = "#403830" }
progress_error  = { fg = "#ffb4ab", bg = "#403830" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#403830" }
cand = { fg = "#f8bb71" }
rest = { fg = "#472a00" }
desc = { fg = "#eee0d4" }
separator = " ▶ "
separator_style = { fg = "#eee0d4" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#bccd9e" }
title_warn  = { fg = "#f8bb71" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#f8bb71" }
active = { fg = "#bccd9e", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#f8bb71" }
value  = { fg = "#eee0d4" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#f8bb71", bg = "#472a00" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#f8bb71" }
title   = {}
hovered = { fg = "#d7e9b8", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#eee0d4" }
run    = { fg = "#eee0d4" }
footer = { fg = "#3f2d17", bg = "#dfc1a2" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#eee0d4" },
    { url = "*/", fg = "#f8bb71" },
]

# : ]]]
