[colors]
background = "#18120c"
foreground = "#eee0d4"

cursor_bg = "#eee0d4"
cursor_border = "#eee0d4"
cursor_fg = "#18120c"

selection_bg = "#dfc1a2"
selection_fg = "#3f2d17"

split = "#dfc1a2"

ansi = [
    "#ffb4ab",
    "#f8bb71",
    "#dfc1a2",
    "#bccd9e",
    "#663e00",
    "#57432b",
    "#3d4b27",
    "#eee0d4"
]

brights = [
    "#93000a",
    "#ffddb9",
    "#fdddbd",
    "#d7e9b8",
    "#f8bb71",
    "#dfc1a2",
    "#bccd9e",
    "#d4c4b5"
]
