-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#141409",
  base01 = "#0f0f05",
  base02 = "#1c1c11",
  base03 = "#484833",
  base04 = "#cac8ac",
  base05 = "#e6e3d0",
  base06 = "#313124",
  base07 = "#3a3a2d",

  base08 = "#c9ff9c",
  base09 = "#d7ffb5",
  base0A = "#cbcb78",
  base0B = "#f9fb3e",
  base0C = "#9ceb63",
  base0D = "#dcde1a",
  base0E = "#4b4c03",
  base0F = "#bdbd53",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#dcde1a',
  fg = '#434300', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#aeff69',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#939279',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d7ffb5',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#cbcb78',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#616200',
})
