-- Generated by Matugen (Refined)

require("base16-colorscheme").setup({
	base00 = "{{colors.background.default.hex}}",
	base01 = "{{colors.surface_container_lowest.default.hex}}",
	base02 = "{{colors.surface_container_low.default.hex}}",
	base03 = "{{colors.outline_variant.default.hex}}",
	base04 = "{{colors.on_surface_variant.default.hex}}",
	base05 = "{{colors.on_surface.default.hex}}",
	base06 = "{{colors.on_surface.default.hex}}",
	base07 = "{{colors.surface_bright.default.hex}}",

	-- Semantic + balanced accents
	base08 = "{{colors.error.default.hex}}", -- Errors
	base09 = "{{colors.tertiary.default.hex}}", -- Numbers / accents
	base0A = "{{colors.secondary.default.hex}}", -- Types
	base0B = "{{colors.primary.default.hex}}", -- Strings
	base0C = "{{colors.tertiary_container.default.hex}}", -- Constants
	base0D = "{{colors.primary_container.default.hex}}", -- Functions
	base0E = "{{colors.secondary_container.default.hex}}", -- Keywords
	base0F = "{{colors.error_container.default.hex}}", -- Warnings
})

---------------------------------------------------------------------
-- Custom Highlight Fixes (for better readability & contrast)
---------------------------------------------------------------------

local function set_hl_multiple(groups, value)
	for _, group in ipairs(groups) do
		vim.api.nvim_set_hl(0, group, value)
	end
end

-- Better visual selection
vim.api.nvim_set_hl(0, "Visual", {
	bg = "{{colors.primary_container.default.hex}}",
	fg = "{{colors.on_primary_container.default.hex}}",
})

-- Strings (clear and readable)
set_hl_multiple({ "String", "TSString" }, {
	fg = "{{colors.primary.default.hex}}",
})

-- Comments (subtle + italic)
set_hl_multiple({ "Comment", "TSComment" }, {
	fg = "{{colors.outline.default.hex}}",
	italic = true,
})

-- Functions / Methods
set_hl_multiple({ "Function", "TSFunction", "Method", "TSMethod" }, {
	fg = "{{colors.primary_container.default.hex}}",
})

-- Keywords (control flow, etc.)
set_hl_multiple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "{{colors.secondary.default.hex}}",
})

-- Types (structs, classes)
set_hl_multiple({ "Type", "TSType" }, {
	fg = "{{colors.secondary_container.default.hex}}",
})

-- Numbers / constants
set_hl_multiple({ "Number", "Constant", "TSNumber", "TSConstant" }, {
	fg = "{{colors.tertiary.default.hex}}",
})

-- Diagnostics (LSP)
set_hl_multiple({ "DiagnosticError" }, {
	fg = "{{colors.error.default.hex}}",
})

set_hl_multiple({ "DiagnosticWarn" }, {
	fg = "{{colors.error_container.default.hex}}",
})

set_hl_multiple({ "DiagnosticInfo" }, {
	fg = "{{colors.primary.default.hex}}",
})

set_hl_multiple({ "DiagnosticHint" }, {
	fg = "{{colors.secondary.default.hex}}",
})

---------------------------------------------------------------------
-- Optional UI polish
---------------------------------------------------------------------

-- Line numbers (subtle)
vim.api.nvim_set_hl(0, "LineNr", {
	fg = "{{colors.outline_variant.default.hex}}",
})

-- Cursor line number (focused)
vim.api.nvim_set_hl(0, "CursorLineNr", {
	fg = "{{colors.primary.default.hex}}",
	bold = true,
})

-- Split borders
vim.api.nvim_set_hl(0, "VertSplit", {
	fg = "{{colors.surface_container_high.default.hex}}",
})

-- Search highlight
vim.api.nvim_set_hl(0, "Search", {
	bg = "{{colors.secondary_container.default.hex}}",
	fg = "{{colors.on_secondary_container.default.hex}}",
})

-- IncSearch (active search)
vim.api.nvim_set_hl(0, "IncSearch", {
	bg = "{{colors.primary.default.hex}}",
	fg = "{{colors.on_primary.default.hex}}",
})
