-- Generated by Matugen (Refined)

require("base16-colorscheme").setup({
	base00 = "#0d141b",
	base01 = "#080f16",
	base02 = "#151c24",
	base03 = "#3a4857",
	base04 = "#b9c8da",
	base05 = "#dce3ee",
	base06 = "#dce3ee",
	base07 = "#333a42",

	-- Semantic + balanced accents
	base08 = "#ffb4ab", -- Errors
	base09 = "#9ccbfb", -- Numbers / accents
	base0A = "#80d4d7", -- Types
	base0B = "#4cd9de", -- Strings
	base0C = "#124a73", -- Constants
	base0D = "#004f52", -- Functions
	base0E = "#004f52", -- Keywords
	base0F = "#93000a", -- Warnings
})

---------------------------------------------------------------------
-- Custom Highlight Fixes (for better readability & contrast)
---------------------------------------------------------------------

local function set_hl_multiple(groups, value)
	for _, group in ipairs(groups) do
		vim.api.nvim_set_hl(0, group, value)
	end
end

-- Better visual selection
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#004f52",
	fg = "#6ff6fb",
})

-- Strings (clear and readable)
set_hl_multiple({ "String", "TSString" }, {
	fg = "#4cd9de",
})

-- Comments (subtle + italic)
set_hl_multiple({ "Comment", "TSComment" }, {
	fg = "#8492a3",
	italic = true,
})

-- Functions / Methods
set_hl_multiple({ "Function", "TSFunction", "Method", "TSMethod" }, {
	fg = "#004f52",
})

-- Keywords (control flow, etc.)
set_hl_multiple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#80d4d7",
})

-- Types (structs, classes)
set_hl_multiple({ "Type", "TSType" }, {
	fg = "#004f52",
})

-- Numbers / constants
set_hl_multiple({ "Number", "Constant", "TSNumber", "TSConstant" }, {
	fg = "#9ccbfb",
})

-- Diagnostics (LSP)
set_hl_multiple({ "DiagnosticError" }, {
	fg = "#ffb4ab",
})

set_hl_multiple({ "DiagnosticWarn" }, {
	fg = "#93000a",
})

set_hl_multiple({ "DiagnosticInfo" }, {
	fg = "#4cd9de",
})

set_hl_multiple({ "DiagnosticHint" }, {
	fg = "#80d4d7",
})

---------------------------------------------------------------------
-- Optional UI polish
---------------------------------------------------------------------

-- Line numbers (subtle)
vim.api.nvim_set_hl(0, "LineNr", {
	fg = "#3a4857",
})

-- Cursor line number (focused)
vim.api.nvim_set_hl(0, "CursorLineNr", {
	fg = "#4cd9de",
	bold = true,
})

-- Split borders
vim.api.nvim_set_hl(0, "VertSplit", {
	fg = "#242b33",
})

-- Search highlight
vim.api.nvim_set_hl(0, "Search", {
	bg = "#004f52",
	fg = "#9cf1f4",
})

-- IncSearch (active search)
vim.api.nvim_set_hl(0, "IncSearch", {
	bg = "#4cd9de",
	fg = "#003738",
})
