-- Generated by Matugen (Refined)

require("base16-colorscheme").setup({
	base00 = "#18120c",
	base01 = "#130d07",
	base02 = "#211a13",
	base03 = "#504539",
	base04 = "#d4c4b5",
	base05 = "#eee0d4",
	base06 = "#eee0d4",
	base07 = "#403830",

	-- Semantic + balanced accents
	base08 = "#ffb4ab", -- Errors
	base09 = "#bccd9e", -- Numbers / accents
	base0A = "#dfc1a2", -- Types
	base0B = "#f8bb71", -- Strings
	base0C = "#3d4b27", -- Constants
	base0D = "#663e00", -- Functions
	base0E = "#57432b", -- Keywords
	base0F = "#93000a", -- Warnings
})

---------------------------------------------------------------------
-- Custom Highlight Fixes (for better readability & contrast)
---------------------------------------------------------------------

local function set_hl_multiple(groups, value)
	for _, group in ipairs(groups) do
		vim.api.nvim_set_hl(0, group, value)
	end
end

-- Better visual selection
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#663e00",
	fg = "#ffddb9",
})

-- Strings (clear and readable)
set_hl_multiple({ "String", "TSString" }, {
	fg = "#f8bb71",
})

-- Comments (subtle + italic)
set_hl_multiple({ "Comment", "TSComment" }, {
	fg = "#9c8e81",
	italic = true,
})

-- Functions / Methods
set_hl_multiple({ "Function", "TSFunction", "Method", "TSMethod" }, {
	fg = "#663e00",
})

-- Keywords (control flow, etc.)
set_hl_multiple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#dfc1a2",
})

-- Types (structs, classes)
set_hl_multiple({ "Type", "TSType" }, {
	fg = "#57432b",
})

-- Numbers / constants
set_hl_multiple({ "Number", "Constant", "TSNumber", "TSConstant" }, {
	fg = "#bccd9e",
})

-- Diagnostics (LSP)
set_hl_multiple({ "DiagnosticError" }, {
	fg = "#ffb4ab",
})

set_hl_multiple({ "DiagnosticWarn" }, {
	fg = "#93000a",
})

set_hl_multiple({ "DiagnosticInfo" }, {
	fg = "#f8bb71",
})

set_hl_multiple({ "DiagnosticHint" }, {
	fg = "#dfc1a2",
})

---------------------------------------------------------------------
-- Optional UI polish
---------------------------------------------------------------------

-- Line numbers (subtle)
vim.api.nvim_set_hl(0, "LineNr", {
	fg = "#504539",
})

-- Cursor line number (focused)
vim.api.nvim_set_hl(0, "CursorLineNr", {
	fg = "#f8bb71",
	bold = true,
})

-- Split borders
vim.api.nvim_set_hl(0, "VertSplit", {
	fg = "#302921",
})

-- Search highlight
vim.api.nvim_set_hl(0, "Search", {
	bg = "#57432b",
	fg = "#fdddbd",
})

-- IncSearch (active search)
vim.api.nvim_set_hl(0, "IncSearch", {
	bg = "#f8bb71",
	fg = "#472a00",
})
